/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingMachine;

import vendingMachine.model.*;
import javafx.application.Application;
import javafx.stage.Stage;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.*;

import vendingMachine.view.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App extends Application  {
    private Connection connection;
    DatabaseQuery dq;
    DatabaseSetup database;
    Controller controller;

    @Override
    public void start(Stage primaryStage) {

        try {
            connection = DriverManager.getConnection("jdbc:sqlite:database.db");
        } catch (SQLException e) {
            System.err.println("Could not connect to database");
            e.printStackTrace();
        }
        StatementManager statementManager = new StatementManager(connection);
        database = new DatabaseSetup(statementManager);
        dq = new DatabaseQueryImp(statementManager);


        controller = new Controller(dq, primaryStage);
    }

    public static void main(String[] args) {

        Application.launch(args);

    }


    @Override
    public void stop() {
        try {
            connection.close();
            controller.timer.cancel();
            controller.timer.purge();
        } catch (SQLException e) {
            System.err.println("Could not close database:");
            e.printStackTrace();
        }
    }
}